#!/usr/bin/env python3
"""Generate scripts/data/core_en_words.json from embedded high-frequency word list."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "scripts" / "data" / "core_en_words.json"

# word|phonetic|pos|translation
RAW = r"""
the|/ðə/|art.|这；那
be|/biː/|v.|是；存在
to|/tuː/|prep.|向；到
of|/ɒv/|prep.|…的
and|/ænd/|conj.|和；并且
a|/ə/|art.|一个
in|/ɪn/|prep.|在…里
that|/ðæt/|pron.|那；那个
have|/hæv/|v.|有；拥有；经历
I|/aɪ/|pron.|我
it|/ɪt/|pron.|它
for|/fɔː/|prep.|为了；对于
not|/nɒt/|adv.|不
on|/ɒn/|prep.|在…上
with|/wɪð/|prep.|和；带有
he|/hiː/|pron.|他
as|/æz/|adv.|如同
you|/juː/|pron.|你；你们
do|/duː/|v.|做；助动词
at|/æt/|prep.|在
this|/ðɪs/|pron.|这；这个
but|/bʌt/|conj.|但是
his|/hɪz/|pron.|他的
by|/baɪ/|prep.|通过；被
from|/frɒm/|prep.|从
they|/ðeɪ/|pron.|他们
we|/wiː/|pron.|我们
say|/seɪ/|v.|说
her|/hɜː/|pron.|她的；她
she|/ʃiː/|pron.|她
or|/ɔː/|conj.|或者
an|/æn/|art.|一个
will|/wɪl/|v.|将；愿意
my|/maɪ/|pron.|我的
one|/wʌn/|num.|一；一个
all|/ɔːl/|adj.|所有的
would|/wʊd/|v.|将会；愿意
there|/ðeə/|adv.|那里
their|/ðeə/|pron.|他们的
what|/wɒt/|pron.|什么
so|/səʊ/|adv.|如此；所以
up|/ʌp/|adv.|向上
out|/aʊt/|adv.|出去
if|/ɪf/|conj.|如果
about|/əˈbaʊt/|prep.|关于；大约
who|/huː/|pron.|谁
get|/ɡet/|v.|得到；变得
which|/wɪtʃ/|pron.|哪一个
go|/ɡəʊ/|v.|去
me|/miː/|pron.|我（宾格）
when|/wen/|adv.|何时
make|/meɪk/|v.|制作；使
can|/kæn/|v.|能；可以
like|/laɪk/|v.|喜欢；像
time|/taɪm/|n.|时间
no|/nəʊ/|adv.|不
just|/dʒʌst/|adv.|刚刚；仅仅
him|/hɪm/|pron.|他（宾格）
know|/nəʊ/|v.|知道
take|/teɪk/|v.|拿；取
people|/ˈpiːpl/|n.|人们
into|/ˈɪntuː/|prep.|进入
year|/jɪə/|n.|年
your|/jɔː/|pron.|你的
good|/ɡʊd/|adj.|好的
some|/sʌm/|adj.|一些
could|/kʊd/|v.|能够
them|/ðem/|pron.|他们（宾格）
see|/siː/|v.|看见
other|/ˈʌðə/|adj.|其他的
than|/ðæn/|conj.|比
then|/ðen/|adv.|然后
now|/naʊ/|adv.|现在
look|/lʊk/|v.|看
only|/ˈəʊnli/|adv.|仅仅
come|/kʌm/|v.|来
its|/ɪts/|pron.|它的
over|/ˈəʊvə/|prep.|在…上方
think|/θɪŋk/|v.|思考
also|/ˈɔːlsəʊ/|adv.|也
back|/bæk/|adv.|回来
after|/ˈɑːftə/|prep.|在…之后
use|/juːz/|v.|使用
two|/tuː/|num.|二
how|/haʊ/|adv.|如何
our|/ˈaʊə/|pron.|我们的
work|/wɜːk/|v.|工作
first|/fɜːst/|adj.|第一的
well|/wel/|adv.|好地
way|/weɪ/|n.|方式；路
even|/ˈiːvən/|adv.|甚至
new|/njuː/|adj.|新的
want|/wɒnt/|v.|想要
because|/bɪˈkɒz/|conj.|因为
any|/ˈeni/|adj.|任何
these|/ðiːz/|pron.|这些
give|/ɡɪv/|v.|给
day|/deɪ/|n.|天
most|/məʊst/|adv.|最
us|/ʌs/|pron.|我们（宾格）
is|/ɪz/|v.|是
are|/ɑː/|v.|是
was|/wɒz/|v.|是（过去）
were|/wɜː/|v.|是（过去复数）
been|/biːn/|v.|是（完成）
being|/ˈbiːɪŋ/|n.|存在；生物
has|/hæz/|v.|有（三单）
had|/hæd/|v.|有（过去）
having|/ˈhævɪŋ/|v.|拥有（现在分词）
very|/ˈveri/|adv.|非常；很
more|/mɔː/|adv.|更多
much|/mʌtʃ/|adv.|很多
many|/ˈmeni/|adj.|许多
such|/sʌtʃ/|adj.|这样的
own|/əʊn/|adj.|自己的
same|/seɪm/|adj.|相同的
too|/tuː/|adv.|也；太
here|/hɪə/|adv.|这里
where|/weə/|adv.|哪里
why|/waɪ/|adv.|为什么
each|/iːtʃ/|adj.|每个
few|/fjuː/|adj.|少数
little|/ˈlɪtl/|adj.|小的；少的
every|/ˈevri/|adj.|每个
both|/bəʊθ/|adj.|两者
between|/bɪˈtwiːn/|prep.|在…之间
through|/θruː/|prep.|通过
during|/ˈdjʊərɪŋ/|prep.|在…期间
before|/bɪˈfɔː/|prep.|在…之前
without|/wɪˈðaʊt/|prep.|没有
within|/wɪˈðɪn/|prep.|在…之内
against|/əˈɡenst/|prep.|反对；靠着
among|/əˈmʌŋ/|prep.|在…之中
while|/waɪl/|conj.|当…时
although|/ɔːlˈðəʊ/|conj.|虽然
since|/sɪns/|conj.|自从
until|/ənˈtɪl/|conj.|直到
once|/wʌns/|adv.|一次
again|/əˈɡen/|adv.|再次
never|/ˈnevə/|adv.|从不
always|/ˈɔːlweɪz/|adv.|总是
often|/ˈɒfn/|adv.|经常
still|/stɪl/|adv.|仍然
already|/ɔːlˈredi/|adv.|已经
yet|/jet/|adv.|还；然而
perhaps|/pəˈhæps/|adv.|也许
really|/ˈrɪəli/|adv.|真正地
quite|/kwaɪt/|adv.|相当
rather|/ˈrɑːðə/|adv.|相当
almost|/ˈɔːlməʊst/|adv.|几乎
enough|/ɪˈnʌf/|adv.|足够
however|/haʊˈevə/|adv.|然而
therefore|/ˈðeəfɔː/|adv.|因此
thus|/ðʌs/|adv.|因此
else|/els/|adv.|其他
something|/ˈsʌmθɪŋ/|pron.|某事
someone|/ˈsʌmwʌn/|pron.|某人
anything|/ˈeniθɪŋ/|pron.|任何事
everything|/ˈevriθɪŋ/|pron.|一切
nothing|/ˈnʌθɪŋ/|pron.|没有东西
another|/əˈnʌðə/|adj.|另一个
everyone|/ˈevriwʌn/|pron.|每个人
anyone|/ˈeniwʌn/|pron.|任何人
myself|/maɪˈself/|pron.|我自己
yourself|/jɔːˈself/|pron.|你自己
himself|/hɪmˈself/|pron.|他自己
herself|/hɜːˈself/|pron.|她自己
itself|/ɪtˈself/|pron.|它自己
ourselves|/aʊəˈselvz/|pron.|我们自己
themselves|/ðəmˈselvz/|pron.|他们自己
man|/mæn/|n.|男人
woman|/ˈwʊmən/|n.|女人
child|/tʃaɪld/|n.|孩子
world|/wɜːld/|n.|世界
life|/laɪf/|n.|生活；生命
hand|/hænd/|n.|手
part|/pɑːt/|n.|部分
place|/pleɪs/|n.|地方
case|/keɪs/|n.|情况；案例
week|/wiːk/|n.|周
company|/ˈkʌmpəni/|n.|公司
system|/ˈsɪstəm/|n.|系统
program|/ˈprəʊɡræm/|n.|程序；计划
question|/ˈkwestʃən/|n.|问题
government|/ˈɡʌvənmənt/|n.|政府
number|/ˈnʌmbə/|n.|数字
group|/ɡruːp/|n.|组
problem|/ˈprɒbləm/|n.|问题
fact|/fækt/|n.|事实
become|/bɪˈkʌm/|v.|成为
need|/niːd/|v.|需要
feel|/fiːl/|v.|感觉
seem|/siːm/|v.|似乎
leave|/liːv/|v.|离开
put|/pʊt/|v.|放
mean|/miːn/|v.|意味着
keep|/kiːp/|v.|保持
let|/let/|v.|让
begin|/bɪˈɡɪn/|v.|开始
show|/ʃəʊ/|v.|展示
hear|/hɪə/|v.|听见
run|/rʌn/|v.|跑；运行
move|/muːv/|v.|移动
live|/lɪv/|v.|生活
believe|/bɪˈliːv/|v.|相信
hold|/həʊld/|v.|持有
bring|/brɪŋ/|v.|带来
happen|/ˈhæpən/|v.|发生
write|/raɪt/|v.|写
provide|/prəˈvaɪd/|v.|提供
sit|/sɪt/|v.|坐
stand|/stænd/|v.|站立
lose|/luːz/|v.|失去
pay|/peɪ/|v.|支付
meet|/miːt/|v.|遇见
include|/ɪnˈkluːd/|v.|包括
continue|/kənˈtɪnjuː/|v.|继续
set|/set/|v.|设置
learn|/lɜːn/|v.|学习
change|/tʃeɪndʒ/|v.|改变
lead|/liːd/|v.|领导
understand|/ˌʌndəˈstænd/|v.|理解
watch|/wɒtʃ/|v.|观看
follow|/ˈfɒləʊ/|v.|跟随
stop|/stɒp/|v.|停止
create|/kriˈeɪt/|v.|创造
speak|/spiːk/|v.|说话
read|/riːd/|v.|阅读
allow|/əˈlaʊ/|v.|允许
add|/æd/|v.|添加
spend|/spend/|v.|花费
grow|/ɡrəʊ/|v.|成长
open|/ˈəʊpən/|v.|打开
walk|/wɔːk/|v.|走
win|/wɪn/|v.|赢
offer|/ˈɒfə/|v.|提供
remember|/rɪˈmembə/|v.|记得
love|/lʌv/|v.|爱
consider|/kənˈsɪdə/|v.|考虑
appear|/əˈpɪə/|v.|出现
buy|/baɪ/|v.|买
wait|/weɪt/|v.|等待
serve|/sɜːv/|v.|服务
die|/daɪ/|v.|死亡
send|/send/|v.|发送
expect|/ɪkˈspekt/|v.|期望
build|/bɪld/|v.|建造
stay|/steɪ/|v.|停留
fall|/fɔːl/|v.|落下
cut|/kʌt/|v.|切
reach|/riːtʃ/|v.|到达
kill|/kɪl/|v.|杀死
remain|/rɪˈmeɪn/|v.|保持
suggest|/səˈdʒest/|v.|建议
raise|/reɪz/|v.|提高
pass|/pɑːs/|v.|通过
sell|/sel/|v.|卖
require|/rɪˈkwaɪə/|v.|需要
report|/rɪˈpɔːt/|v.|报告
decide|/dɪˈsaɪd/|v.|决定
pull|/pʊl/|v.|拉
big|/bɪɡ/|adj.|大的
long|/lɒŋ/|adj.|长的
great|/ɡreɪt/|adj.|伟大的
high|/haɪ/|adj.|高的
small|/smɔːl/|adj.|小的
large|/lɑːdʒ/|adj.|大的
next|/nekst/|adj.|下一个
early|/ˈɜːli/|adj.|早的
young|/jʌŋ/|adj.|年轻的
important|/ɪmˈpɔːtnt/|adj.|重要的
public|/ˈpʌblɪk/|adj.|公共的
bad|/bæd/|adj.|坏的
able|/ˈeɪbl/|adj.|能够的
human|/ˈhjuːmən/|adj.|人类的
local|/ˈləʊkl/|adj.|本地的
sure|/ʃʊə/|adj.|确定的
clear|/klɪə/|adj.|清楚的
recent|/ˈriːsnt/|adj.|最近的
strong|/strɒŋ/|adj.|强壮的
possible|/ˈpɒsəbl/|adj.|可能的
whole|/həʊl/|adj.|整个的
free|/friː/|adj.|自由的
full|/fʊl/|adj.|满的
special|/ˈspeʃl/|adj.|特别的
easy|/ˈiːzi/|adj.|容易的
hard|/hɑːd/|adj.|困难的
real|/rɪəl/|adj.|真实的
best|/best/|adj.|最好的
better|/ˈbetə/|adj.|更好的
different|/ˈdɪfrənt/|adj.|不同的
social|/ˈsəʊʃl/|adj.|社会的
political|/pəˈlɪtɪkl/|adj.|政治的
economic|/ˌiːkəˈnɒmɪk/|adj.|经济的
international|/ˌɪntəˈnæʃnəl/|adj.|国际的
national|/ˈnæʃnəl/|adj.|国家的
common|/ˈkɒmən/|adj.|常见的
general|/ˈdʒenrəl/|adj.|一般的
particular|/pəˈtɪkjələ/|adj.|特别的
major|/ˈmeɪdʒə/|adj.|主要的
available|/əˈveɪləbl/|adj.|可用的
likely|/ˈlaɪkli/|adj.|可能的
certain|/ˈsɜːtn/|adj.|确定的
various|/ˈveəriəs/|adj.|各种各样的
similar|/ˈsɪmələ/|adj.|相似的
necessary|/ˈnesəsəri/|adj.|必要的
personal|/ˈpɜːsənl/|adj.|个人的
single|/ˈsɪŋɡl/|adj.|单一的
simple|/ˈsɪmpl/|adj.|简单的
natural|/ˈnætʃrəl/|adj.|自然的
physical|/ˈfɪzɪkl/|adj.|身体的；物理的
mental|/ˈmentl/|adj.|精神的
medical|/ˈmedɪkl/|adj.|医学的
financial|/faɪˈnænʃl/|adj.|金融的
legal|/ˈliːɡl/|adj.|法律的
cultural|/ˈkʌltʃərəl/|adj.|文化的
historical|/hɪˈstɒrɪkl/|adj.|历史的
scientific|/ˌsaɪənˈtɪfɪk/|adj.|科学的
technical|/ˈteknɪkl/|adj.|技术的
modern|/ˈmɒdn/|adj.|现代的
traditional|/trəˈdɪʃnəl/|adj.|传统的
global|/ˈɡləʊbl/|adj.|全球的
central|/ˈsentrəl/|adj.|中央的
final|/ˈfaɪnl/|adj.|最终的
main|/meɪn/|adj.|主要的
current|/ˈkʌrənt/|adj.|当前的
future|/ˈfjuːtʃə/|n.|未来
past|/pɑːst/|n.|过去
present|/ˈpreznt/|n.|现在
history|/ˈhɪstri/|n.|历史
research|/rɪˈsɜːtʃ/|n.|研究
study|/ˈstʌdi/|n.|学习；研究
student|/ˈstjuːdnt/|n.|学生
teacher|/ˈtiːtʃə/|n.|教师
school|/skuːl/|n.|学校
university|/ˌjuːnɪˈvɜːsəti/|n.|大学
education|/ˌedʒuˈkeɪʃn/|n.|教育
knowledge|/ˈnɒlɪdʒ/|n.|知识
information|/ˌɪnfəˈmeɪʃn/|n.|信息
data|/ˈdeɪtə/|n.|数据
technology|/tekˈnɒlədʒi/|n.|技术
computer|/kəmˈpjuːtə/|n.|计算机
internet|/ˈɪntənet/|n.|互联网
network|/ˈnetwɜːk/|n.|网络
software|/ˈsɒftweə/|n.|软件
machine|/məˈʃiːn/|n.|机器
learning|/ˈlɜːnɪŋ/|n.|学习
language|/ˈlæŋɡwɪdʒ/|n.|语言
english|/ˈɪŋɡlɪʃ/|n.|英语
word|/wɜːd/|n.|单词
sentence|/ˈsentəns/|n.|句子
text|/tekst/|n.|文本
meaning|/ˈmiːnɪŋ/|n.|意义
example|/ɪɡˈzɑːmpl/|n.|例子
method|/ˈmeθəd/|n.|方法
process|/ˈprəʊses/|n.|过程
result|/rɪˈzʌlt/|n.|结果
effect|/ɪˈfekt/|n.|效果
cause|/kɔːz/|n.|原因
reason|/ˈriːzn/|n.|理由
idea|/aɪˈdɪə/|n.|想法
theory|/ˈθɪəri/|n.|理论
practice|/ˈpræktɪs/|n.|实践
experience|/ɪkˈspɪəriəns/|n.|经验
skill|/skɪl/|n.|技能
ability|/əˈbɪləti/|n.|能力
effort|/ˈefət/|n.|努力
success|/səkˈses/|n.|成功
failure|/ˈfeɪljə/|n.|失败
risk|/rɪsk/|n.|风险
value|/ˈvæljuː/|n.|价值
quality|/ˈkwɒləti/|n.|质量
price|/praɪs/|n.|价格
market|/ˈmɑːkɪt/|n.|市场
business|/ˈbɪznəs/|n.|商业
industry|/ˈɪndəstri/|n.|工业
energy|/ˈenədʒi/|n.|能源
environment|/ɪnˈvaɪrənmənt/|n.|环境
nature|/ˈneɪtʃə/|n.|自然
water|/ˈwɔːtə/|n.|水
food|/fuːd/|n.|食物
health|/helθ/|n.|健康
body|/ˈbɒdi/|n.|身体
mind|/maɪnd/|n.|思想
heart|/hɑːt/|n.|心脏
family|/ˈfæməli/|n.|家庭
friend|/frend/|n.|朋友
community|/kəˈmjuːnəti/|n.|社区
society|/səˈsaɪəti/|n.|社会
culture|/ˈkʌltʃə/|n.|文化
country|/ˈkʌntri/|n.|国家
city|/ˈsɪti/|n.|城市
area|/ˈeəriə/|n.|区域
state|/steɪt/|n.|状态；州
law|/lɔː/|n.|法律
right|/raɪt/|n.|权利
power|/ˈpaʊə/|n.|权力
policy|/ˈpɒləsi/|n.|政策
interest|/ˈɪntrest/|n.|兴趣
support|/səˈpɔːt/|n.|支持
development|/dɪˈveləpmənt/|n.|发展
growth|/ɡrəʊθ/|n.|增长
increase|/ɪnˈkriːs/|v.|增加
decrease|/dɪˈkriːs/|v.|减少
improve|/ɪmˈpruːv/|v.|改善
reduce|/rɪˈdjuːs/|v.|减少
develop|/dɪˈveləp/|v.|发展
produce|/prəˈdjuːs/|v.|生产
design|/dɪˈzaɪn/|v.|设计
manage|/ˈmænɪdʒ/|v.|管理
control|/kənˈtrəʊl/|v.|控制
analyze|/ˈænəlaɪz/|v.|分析
explain|/ɪkˈspleɪn/|v.|解释
describe|/dɪˈskraɪb/|v.|描述
discuss|/dɪˈskʌs/|v.|讨论
compare|/kəmˈpeə/|v.|比较
identify|/aɪˈdentɪfaɪ/|v.|识别
define|/dɪˈfaɪn/|v.|定义
establish|/ɪˈstæblɪʃ/|v.|建立
maintain|/meɪnˈteɪn/|v.|维持
achieve|/əˈtʃiːv/|v.|实现
obtain|/əbˈteɪn/|v.|获得
contain|/kənˈteɪn/|v.|包含
represent|/ˌreprɪˈzent/|v.|代表
indicate|/ˈɪndɪkeɪt/|v.|表明
demonstrate|/ˈdemənstreɪt/|v.|证明
assume|/əˈsjuːm/|v.|假设
argue|/ˈɑːɡjuː/|v.|论证
claim|/kleɪm/|v.|声称
focus|/ˈfəʊkəs/|v.|聚焦
apply|/əˈplaɪ/|v.|应用
respond|/rɪˈspɒnd/|v.|回应
accept|/əkˈsept/|v.|接受
avoid|/əˈvɔɪd/|v.|避免
prevent|/prɪˈvent/|v.|预防
protect|/prəˈtekt/|v.|保护
express|/ɪkˈspres/|v.|表达
perform|/pəˈfɔːm/|v.|执行
complete|/kəmˈpliːt/|v.|完成
finish|/ˈfɪnɪʃ/|v.|完成
start|/stɑːt/|v.|开始
end|/end/|v.|结束
return|/rɪˈtɜːn/|v.|返回
turn|/tɜːn/|v.|转动
break|/breɪk/|v.|打破
close|/kləʊz/|v.|关闭
carry|/ˈkæri/|v.|携带
drive|/draɪv/|v.|驾驶
fly|/flaɪ/|v.|飞
travel|/ˈtrævl/|v.|旅行
visit|/ˈvɪzɪt/|v.|访问
call|/kɔːl/|v.|呼叫
help|/help/|v.|帮助
try|/traɪ/|v.|尝试
find|/faɪnd/|v.|找到
tell|/tel/|v.|告诉
ask|/ɑːsk/|v.|问
answer|/ˈɑːnsə/|v.|回答
play|/pleɪ/|v.|玩
enjoy|/ɪnˈdʒɔɪ/|v.|享受
hope|/həʊp/|v.|希望
wish|/wɪʃ/|v.|希望
fear|/fɪə/|v.|害怕
worry|/ˈwʌri/|v.|担心
care|/keə/|v.|关心
share|/ʃeə/|v.|分享
choose|/tʃuːz/|v.|选择
prefer|/prɪˈfɜː/|v.|更喜欢
agree|/əˈɡriː/|v.|同意
disagree|/ˌdɪsəˈɡriː/|v.|不同意
succeed|/səkˈsiːd/|v.|成功
fail|/feɪl/|v.|失败
exist|/ɪɡˈzɪst/|v.|存在
occur|/əˈkɜː/|v.|发生
form|/fɔːm/|v.|形成
base|/beɪs/|v.|基于
depend|/dɪˈpend/|v.|依赖
involve|/ɪnˈvɒlv/|v.|涉及
relate|/rɪˈleɪt/|v.|关联
refer|/rɪˈfɜː/|v.|提及
recognize|/ˈrekəɡnaɪz/|v.|识别
notice|/ˈnəʊtɪs/|v.|注意到
observe|/əbˈzɜːv/|v.|观察
measure|/ˈmeʒə/|v.|测量
test|/test/|v.|测试
check|/tʃek/|v.|检查
solve|/sɒlv/|v.|解决
deal|/diːl/|v.|处理
handle|/ˈhændl/|v.|处理
face|/feɪs/|v.|面对
cover|/ˈkʌvə/|v.|覆盖
draw|/drɔː/|v.|画；拉
push|/pʊʃ/|v.|推
throw|/θrəʊ/|v.|扔
catch|/kætʃ/|v.|抓住
hit|/hɪt/|v.|打
fight|/faɪt/|v.|战斗
attack|/əˈtæk/|v.|攻击
defend|/dɪˈfend/|v.|防御
save|/seɪv/|v.|保存；拯救
store|/stɔː/|v.|存储
record|/rɪˈkɔːd/|v.|记录
publish|/ˈpʌblɪʃ/|v.|出版
release|/rɪˈliːs/|v.|发布
introduce|/ˌɪntrəˈdjuːs/|v.|介绍
replace|/rɪˈpleɪs/|v.|替换
remove|/rɪˈmuːv/|v.|移除
combine|/kəmˈbaɪn/|v.|结合
connect|/kəˈnekt/|v.|连接
separate|/ˈsepəreɪt/|v.|分离
divide|/dɪˈvaɪd/|v.|划分
extend|/ɪkˈstend/|v.|延伸
expand|/ɪkˈspænd/|v.|扩展
limit|/ˈlɪmɪt/|v.|限制
restrict|/rɪˈstrɪkt/|v.|限制
ensure|/ɪnˈʃʊə/|v.|确保
enable|/ɪˈneɪbl/|v.|使能够
encourage|/ɪnˈkʌrɪdʒ/|v.|鼓励
influence|/ˈɪnfluəns/|v.|影响
affect|/əˈfekt/|v.|影响
impact|/ˈɪmpækt/|v.|冲击
benefit|/ˈbenɪfɪt/|v.|受益
challenge|/ˈtʃælɪndʒ/|n.|挑战
opportunity|/ˌɒpəˈtjuːnəti/|n.|机会
advantage|/ədˈvɑːntɪdʒ/|n.|优势
disadvantage|/ˌdɪsədˈvɑːntɪdʒ/|n.|劣势
difference|/ˈdɪfrəns/|n.|差异
relationship|/rɪˈleɪʃnʃɪp/|n.|关系
communication|/kəˌmjuːnɪˈkeɪʃn/|n.|交流
decision|/dɪˈsɪʒn/|n.|决定
action|/ˈækʃn/|n.|行动
activity|/ækˈtɪvəti/|n.|活动
event|/ɪˈvent/|n.|事件
issue|/ˈɪʃuː/|n.|问题
matter|/ˈmætə/|n.|事情
subject|/ˈsʌbdʒɪkt/|n.|主题
topic|/ˈtɒpɪk/|n.|话题
content|/ˈkɒntent/|n.|内容
context|/ˈkɒntekst/|n.|语境
structure|/ˈstrʌktʃə/|n.|结构
function|/ˈfʌŋkʃn/|n.|功能
feature|/ˈfiːtʃə/|n.|特征
element|/ˈelɪmənt/|n.|元素
factor|/ˈfæktə/|n.|因素
source|/sɔːs/|n.|来源
resource|/rɪˈsɔːs/|n.|资源
material|/məˈtɪəriəl/|n.|材料
evidence|/ˈevɪdəns/|n.|证据
argument|/ˈɑːɡjumənt/|n.|论点
conclusion|/kənˈkluːʒn/|n.|结论
summary|/ˈsʌməri/|n.|总结
analysis|/əˈnæləsɪs/|n.|分析
strategy|/ˈstrætədʒi/|n.|策略
goal|/ɡəʊl/|n.|目标
purpose|/ˈpɜːpəs/|n.|目的
task|/tɑːsk/|n.|任务
project|/ˈprɒdʒekt/|n.|项目
plan|/plæn/|n.|计划
stage|/steɪdʒ/|n.|阶段
step|/step/|n.|步骤
level|/ˈlevl/|n.|水平
degree|/dɪˈɡriː/|n.|程度
rate|/reɪt/|n.|比率
amount|/əˈmaʊnt/|n.|数量
size|/saɪz/|n.|大小
length|/leŋθ/|n.|长度
distance|/ˈdɪstəns/|n.|距离
speed|/spiːd/|n.|速度
weight|/weɪt/|n.|重量
temperature|/ˈtemprətʃə/|n.|温度
pressure|/ˈpreʃə/|n.|压力
force|/fɔːs/|n.|力量
light|/laɪt/|n.|光
sound|/saʊnd/|n.|声音
color|/ˈkʌlə/|n.|颜色
colour|/ˈkʌlə/|n.|颜色
black|/blæk/|adj.|黑色的
white|/waɪt/|adj.|白色的
red|/red/|adj.|红色的
blue|/bluː/|adj.|蓝色的
green|/ɡriːn/|adj.|绿色的
yellow|/ˈjeləʊ/|adj.|黄色的
dark|/dɑːk/|adj.|黑暗的
deep|/diːp/|adj.|深的
wide|/waɪd/|adj.|宽的
narrow|/ˈnærəʊ/|adj.|窄的
thick|/θɪk/|adj.|厚的
thin|/θɪn/|adj.|薄的
heavy|/ˈhevi/|adj.|重的
fast|/fɑːst/|adj.|快的
slow|/sləʊ/|adj.|慢的
quick|/kwɪk/|adj.|快的
hot|/hɒt/|adj.|热的
cold|/kəʊld/|adj.|冷的
warm|/wɔːm/|adj.|温暖的
cool|/kuːl/|adj.|凉爽的
dry|/draɪ/|adj.|干燥的
wet|/wet/|adj.|湿的
clean|/kliːn/|adj.|干净的
dirty|/ˈdɜːti/|adj.|脏的
safe|/seɪf/|adj.|安全的
dangerous|/ˈdeɪndʒərəs/|adj.|危险的
true|/truː/|adj.|真实的
false|/fɔːls/|adj.|错误的
correct|/kəˈrekt/|adj.|正确的
wrong|/rɒŋ/|adj.|错误的
positive|/ˈpɒzətɪv/|adj.|积极的
negative|/ˈneɡətɪv/|adj.|消极的
active|/ˈæktɪv/|adj.|活跃的
passive|/ˈpæsɪv/|adj.|被动的
direct|/dəˈrekt/|adj.|直接的
indirect|/ˌɪndəˈrekt/|adj.|间接的
formal|/ˈfɔːml/|adj.|正式的
informal|/ɪnˈfɔːml/|adj.|非正式的
basic|/ˈbeɪsɪk/|adj.|基本的
advanced|/ədˈvɑːnst/|adj.|高级的
primary|/ˈpraɪməri/|adj.|主要的
secondary|/ˈsekəndri/|adj.|次要的
additional|/əˈdɪʃənl/|adj.|额外的
extra|/ˈekstrə/|adj.|额外的
total|/ˈtəʊtl/|adj.|总的
average|/ˈævərɪdʒ/|adj.|平均的
maximum|/ˈmæksɪməm/|adj.|最大的
minimum|/ˈmɪnɪməm/|adj.|最小的
equal|/ˈiːkwəl/|adj.|相等的
opposite|/ˈɒpəzɪt/|adj.|相反的
alone|/əˈləʊn/|adj.|单独的
together|/təˈɡeðə/|adv.|一起
apart|/əˈpɑːt/|adv.|分开
away|/əˈweɪ/|adv.|离开
near|/nɪə/|adv.|附近
far|/fɑː/|adv.|远
above|/əˈbʌv/|prep.|在…上方
below|/bɪˈləʊ/|prep.|在…下方
under|/ˈʌndə/|prep.|在…下
behind|/bɪˈhaɪnd/|prep.|在…后面
front|/frʌnt/|n.|前面
side|/saɪd/|n.|边
top|/tɒp/|n.|顶部
bottom|/ˈbɒtəm/|n.|底部
middle|/ˈmɪdl/|n.|中间
center|/ˈsentə/|n.|中心
centre|/ˈsentə/|n.|中心
corner|/ˈkɔːnə/|n.|角落
line|/laɪn/|n.|线
point|/pɔɪnt/|n.|点
surface|/ˈsɜːfɪs/|n.|表面
protocol|/ˈprəʊtəkɒl/|n.|协议
macro|/ˈmækrəʊ/|n.|宏
volatility|/ˌvɒləˈtɪləti/|n.|波动性
identification|/aɪˌdentɪfɪˈkeɪʃn/|n.|识别
"""


def main() -> None:
    words: list[dict] = []
    seen: set[str] = set()
    for line in RAW.strip().splitlines():
        parts = line.split("|")
        if len(parts) != 4:
            continue
        w, ph, pos, trans = parts
        w = w.strip().lower()
        if w in seen:
            continue
        seen.add(w)
        gloss = trans.split("；")[0]
        words.append(
            {
                "word": w,
                "phonetic": ph,
                "pos": pos,
                "translation": trans,
                "kaoyan_gloss": gloss,
                "tag": "core",
            }
        )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(words, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {len(words)} words -> {OUT}")


if __name__ == "__main__":
    main()
